site_name: Sistema de Gesti贸n de Pedidos
theme:
  name: material
  features:
    - navigation.sections  # Agrupa visualmente por secciones
    - navigation.indexes   # Permite que la carpeta misma sea un link (Landing)
  palette: 
    primary: indigo
    scheme: default

# Configuraci贸n vital para Mermaid
markdown_extensions:
  - attr_list              # Necesario para redimensionar im谩genes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Inicio: index.md
  -  rea de Diagramas:
      - Resumen Visual: diagramas/index.md
      - Arquitectura C4: diagramas/arquitectura.md
      - API de Pagos (Secuencia): diagramas/secuencia-pagos.md
  -  Centro de Documentos:
      - Vista General: documentos/index.md
      - Gu铆a con Im谩genes: documentos/guia_usuario.md
      - Archivos PDF: documentos/manual_legal.md
      - Flujo de Aprobaci贸n (Proceso): documentos/proceso-aprobacion.md
      - Especificaci贸n T茅cnica: documentos/especificaciones.md